/* SPDX-License-Identifier: AGPLv3
 *
 * Copyright (c) 2026 Askimo
 */
package io.askimo.ui.service

import io.askimo.core.logging.logger
import java.io.File
import java.time.Year

/**
 * Exports an AI chat message (markdown content) to PDF or Word.
 *
 * Uses the shared [PdfExporter] and [WordExporter] for rendering — the same
 * engines used by the plan export feature.
 */
object MessageExportService {

    private val log = logger<MessageExportService>()

    enum class ExportFormat { PDF, WORD }

    private val COPYRIGHT = "Generated by Askimo · Copyright © ${Year.now().value} · https://askimo.io"

    /**
     * Exports [content] (markdown) to [targetFile] in the given [format].
     *
     * @param content   Raw markdown content of the AI message.
     * @param targetFile Destination file (created/overwritten).
     * @param format    [ExportFormat.PDF] or [ExportFormat.WORD].
     */
    suspend fun export(
        content: String,
        targetFile: File,
        format: ExportFormat = ExportFormat.PDF,
    ) {
        log.info("Exporting AI message to {} ({})", format, targetFile.absolutePath)
        when (format) {
            ExportFormat.PDF -> PdfExporter.export(content, COPYRIGHT, targetFile)
            ExportFormat.WORD -> WordExporter.export(content, COPYRIGHT, targetFile)
        }
        log.info("AI message exported -> {}", targetFile.absolutePath)
    }
}
