/* SPDX-License-Identifier: AGPLv3
 *
 * Copyright (c) 2026 Askimo
 */
package io.askimo.ui.plan

import io.askimo.core.logging.logger
import io.askimo.core.plan.PlanRunResult
import io.askimo.core.plan.PlanStepEvent
import io.askimo.core.plan.domain.PlanDef
import io.askimo.ui.service.PdfExporter
import io.askimo.ui.service.WordExporter
import java.io.File
import java.time.Year

/**
 * Orchestrates plan export to PDF or Word (.docx).
 *
 * This object is the single public entry point for callers; format-specific
 * rendering is delegated to [PdfExporter] (OpenPDF) and [WordExporter]
 * (Apache POI) respectively.
 */
object PlanExportService {

    private val log = logger<PlanExportService>()

    enum class ExportMode { RESULT_ONLY, FULL_RUN }
    enum class ExportFormat { PDF, WORD }

    private val COPYRIGHT = "Generated by Askimo · Copyright © ${Year.now().value} · https://askimo.io"

    suspend fun export(
        plan: PlanDef,
        inputValues: Map<String, String>,
        stepProgress: List<PlanStepEvent>,
        result: PlanRunResult,
        mode: ExportMode,
        format: ExportFormat,
        targetFile: File,
    ) {
        val markdown = buildMarkdown(plan, inputValues, stepProgress, result, mode)
        when (format) {
            ExportFormat.PDF -> PdfExporter.export(markdown, COPYRIGHT, targetFile)
            ExportFormat.WORD -> WordExporter.export(markdown, COPYRIGHT, targetFile)
        }
        log.info("Exported plan '{}' ({}, {}) to {}", plan.id, mode, format, targetFile.absolutePath)
    }

    private fun buildMarkdown(
        plan: PlanDef,
        inputValues: Map<String, String>,
        stepProgress: List<PlanStepEvent>,
        result: PlanRunResult,
        mode: ExportMode,
    ): String = buildString {
        if (mode == ExportMode.FULL_RUN) {
            if (inputValues.isNotEmpty()) {
                append("## Inputs\n\n")
                inputValues.forEach { (key, value) ->
                    val label = plan.inputs.find { it.key == key }?.label ?: key
                    append("- **$label**: $value\n")
                }
                append("\n")
            }

            val orderedSteps = linkedMapOf<String, PlanStepEvent>()
            stepProgress.forEach { event ->
                if (orderedSteps[event.stepName] == null || event !is PlanStepEvent.Started) {
                    orderedSteps[event.stepName] = event
                }
            }

            // The last completed step's output IS the result — suppress it in the
            // Steps section to avoid duplicating it in the Result section below.
            val lastCompletedStepName = orderedSteps.values
                .filterIsInstance<PlanStepEvent.Completed>()
                .lastOrNull()
                ?.stepName

            if (orderedSteps.isNotEmpty()) {
                append("## Steps\n\n")
                orderedSteps.values.forEach { event ->
                    val status = when (event) {
                        is PlanStepEvent.Completed -> "[OK ${event.durationMs}ms]"
                        is PlanStepEvent.Failed -> "[FAILED ${event.durationMs}ms]"
                        is PlanStepEvent.Started -> "[running]"
                        is PlanStepEvent.WaitingForInput -> "[waiting for input]"
                    }
                    append("### ${event.stepName}  $status\n\n")
                    when (event) {
                        is PlanStepEvent.Completed -> {
                            // Skip output for the last step — it will appear in the Result section
                            if (event.stepName != lastCompletedStepName) {
                                event.output?.toString()?.trim()
                                    ?.takeIf { it.isNotBlank() }?.let { append("$it\n\n") }
                            }
                        }

                        is PlanStepEvent.Failed ->
                            append("> Error: ${event.error.message ?: event.error.javaClass.simpleName}\n\n")

                        is PlanStepEvent.WaitingForInput ->
                            append("> Question: ${event.question}\n\n")

                        else -> Unit
                    }
                }
            }
            append("---\n\n## Result\n\n")
        }
        append(result.output)
    }
}
