package io.askimo.core.providers

import dev.langchain4j.service.TokenStream
import dev.langchain4j.service.UserMessage

/**
 * Defines the contract for services that provide chat functionality with language models.
 *
 * This interface abstracts the underlying implementation details of different language model
 * providers, allowing the application to interact with various chat models through a unified API.
 */
interface ChatService {
    /**
     * Streams the response from a language model for the given prompt.
     *
     * This method provides an asynchronous streaming API that returns tokens as they
     * are generated by the language model.
     *
     * @param prompt The input text to send to the language model
     * @return A [TokenStream] that emits tokens as they are generated
     */
    fun stream(
        @UserMessage prompt: String,
    ): TokenStream
}
